version: '3'

services:
  # goBalance:
  #   container_name: wallet-balances
  #   platform: linux/amd64
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3003:8080

  mysql:
    image: mysql:5.7
    container_name: mysql-balances
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: balance
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
